name: travel_mate
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  latlong2: ^0.8.0
  cupertino_icons: ^1.0.2
  flutter_map: ^4.0.0
  flutter_bloc: ^8.1.5
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.16.1
  firebase_ui_firestore: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/login_plane.png
    - assets/avatar.png
    - assets/google.png
